.catalog:
  name: "Asean UI"
  version: "0.0.1"
  description: "Asean dependencies"
  questions:
  - variable: "RANCHER_SERVER_IP"
    label: "Rancher Server IP"
    description: "IP Address of the rancher server, no HTTP or slashes. This is only required for users that have enabled metrics to be exported by Rancher"
    default: "0.0.0.0"
    required: true
    type: "string"
  - variable: "RANCHER_SERVER_PORT"
    label: "Rancher Server PORT"
    description: ""
    default: "8080"
    required: true
    type: "string"
  - variable: "ALERT_IP"
    label: "Alert IP Address"
    description: "Alert manager IP address"
    default: ""
    required: true
    type: "string"
  - variable: "ALERT_PORT"
    label: "Alert Port"
    description: "Alert Manager Port"
    default: "8888"
    required: true
    type: "string"
  - variable: "HARBOR_IP"
    label: "Harbor IP Address"
    description: "Harbor IP address"
    default: ""
    required: true
    type: "string"
  - variable: "HARBOR_PORT"
    label: "Harbor Port"
    description: "Harbor server Port"
    default: "80"
    required: true
    type: "string"

asean-ui:
  scale: 1
  health_check:
    port: 3001
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
  start_on_create: true
  metadata:
    rancher_ip: ${RANCHER_SERVER_IP}
    rancher_port: ${RANCHER_SERVER_PORT}
    alert_ip: ${ALERT_IP}
    alert_port: ${ALERT_PORT}
    harbor_ip: ${HARBOR_IP}
    harbor_port: ${HARBOR_PORT}
